
#   ____        _   _                 _
#  / __ \      | | (_)               | |
# | |  | |_ __ | |_ _ _ __ ___   __ _| |
# | |  | | '_ \| __| | '_ ` _ \ / _` | |
# | |__| | |_) | |_| | | | | | | (_| | |
#  \____/| .__/ \__|_|_| |_| |_|\__,_|_|
#        | |
#  __  __|_|___ _______ _____
# |  \/  |/ __ \__   __|  __ \
# | \  / | |  | | | |  | |  | |
# | |\/| | |  | | | |  | |  | |
# | |  | | |__| | | |  | |__| |
# |_|  |_|\____/  |_|  |_____/
#

# Colors:
# -> &0 = Black
# -> &1 = Dark Blue
# -> &2 = Dark Green
# -> &3 = Dark Aqua
# -> &4 = Dark Red
# -> &5 = Dark Purple
# -> &6 = Gold
# -> &7 = Gray
# -> &8 = Dark Gray
# -> &9 = Blue
# -> &a = Green
# -> &b = Aqua
# -> &c = Red
# -> &d = Light Purple
# -> &e = Yellow
# -> &f = White

motd:
  1: '&aExample'
  2: '&eMotd'

players: 2020 # No modify slots only change number :)